### ISSUE TITLE
MySQL helm chart eval

### ISSUE THREAD

**Issue by metadave** [mozmeao/infra#359]
- investigate PV/PVC for MySQL
- investigate Helm chart and how it can be configured to use with MDN.

**Comment by escattone** [comment]
I tried dynamic provisioning in the Virginia cluster (which I think is at Kubernetes 1.5 -- in version 1.6 dynamic provisioning has moved from `beta` to `stable`), using this:
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast-for-db
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  zones: us-east-1b, us-east-1c, us-east-1d
  iopsPerGB: "10"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: test-ebs-claim
    annotations:
      volume.beta.kubernetes.io/storage-class: fast-for-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: test-ebs-pod
spec:
  volumes:
    - name: test-ebs-store
      persistentVolumeClaim:
       claimName: test-ebs-claim
  containers:
    - name: test-ebs-container
      image: nginx
      volumeMounts:
        - name: test-ebs-store
          mountPath: "/"
```

but it doesn't work. The PVC never leaves the `pending` state. No matter though, because I don't think we should use dynamic provisioning for now. It appears that automatically provisioned PV's are created with a reclaim policy of `delete`, and if we want something different (we'd want `retain`), we'd have to edit the PV after it has been created (which seems super awkward).

See http://blog.kubernetes.io/2017/03/dynamic-provisioning-and-storage-classes-kubernetes.html

> All PVs have a reclaim policy associated with them that dictates what happens to a PV once it becomes released from a claim (see user-guide). Since the goal of dynamic provisioning is to completely automate the lifecycle of storage resources, the default reclaim policy for dynamically provisioned volumes is “delete”. This means that when a PersistentVolumeClaim (PVC) is released, the dynamically provisioned volume is de-provisioned (deleted) on the storage provider and the data is likely irretrievable. If this is not the desired behavior, the user must change the reclaim policy on the corresponding PersistentVolume (PV) object after the volume is provisioned.

**Comment by escattone** [comment]
So my thinking is that we should (at least for now), create one or more of our own PV's (that use EBS) for use by the MySQL instance(s).

**Comment by metadave** [comment]
@escattone 👍, then we can backup EBS to S3 for cheaper storage.

**Comment by escattone** [comment]
Ok, here's my latest discovery related to PV's, PVC's, and the MySQL Helm chart. If I first setup a PV and then MySQL like this:
```
make k8s-pv-db
make k8s-mysql
```
It works great. The PV gets created with a storage class of `mdn-fast-db`, and then the Helm chart creates a PVC which requests a PV with the `mdn-fast-db` storage class, and the PVC and PV are successfully bound.

However when I delete the MySQL instance and attempt to recreate it, the PVC remains in a pending state. It is never re-bound to the PV. I discovered that this is because the PV remains in a `released` state and is NOT available for re-binding. I need to discover how to get the PV back to a state of `available`.

**Comment by escattone** [comment]
Just as a reminder, when we move to the new Portland cluster, assuming it's running a newer version of Kubernetes, I'll have to change the storage class identifiers from annotations:
```
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: mdn-fast-db
```
 to the newer:
```
spec:
  storageClassName: mdn-fast-db
```

**Comment by escattone** [comment]
[This](https://github.com/kubernetes/kubernetes/issues/20753) seems like the same thing I'm seeing (in the Virginia cluster, which is K8s 1.5 I think).

**Comment by escattone** [comment]
[This](https://github.com/kubernetes/kubernetes/issues/33102) is another interesting discussion of the same issue of making released PV's available again. What I learned from the discussion was that a PV with a `persistentVolumeReclaimPolicy` of `retain` means that once the PV is released from an existing claim, it remains in the `released` state forever. The PV must be deleted and re-created in order to be re-claimed. Strange.

**Comment by metadave** [comment]
>Just as a reminder, when we move to the new Portland cluster, assuming it's running a newer version of Kubernetes, I'll have to change the storage class identifiers from annotations: ...

We'll have to keep in mind that our clusters most likely will not have matching K8s version, so if we can come up with a universal solution, that might be best.

**Comment by metadave** [comment]
@escattone interesting find wrt `retain` behavior, as that's what I initially experimented with for the EFS mount awhile back. Do you think just documenting this somewhere in a "runbook" for support would be helpful? Something like: `in an emergency, delete and recreate the PV/PVC`, (although I'm not sure what cascading effects that would cause w/ running pods.

**Comment by escattone** [comment]
@metadave I realized last night that I was thinking this could be a problem if the MySQL pod goes down and is recreated, but of course (I'm slow sometimes) the MySQL pod going down has no effect on the MySQL PVC, so it remains bound to the PV. The only issue is if the MySQL PVC is deleted (e.g., if someone uses the `make k8s-delete-mysql` command, which in turn calls the `helm delete --purge ...` command), we'll have to make sure that the PV is recreated as well. I'll build that into the `Makefile`.

**Comment by escattone** [comment]
@metadave Missed replying to your earlier comment about a "universal solution". Given that we may have some clusters above 1.5 but not yet at 1.7 , we can continue to use the annotation approach for storage classes as 1.7 still supports that (although I think support for that drops in the next release).

**Comment by escattone** [comment]
@metadave Regarding our problems with our MySQL Helm chart work earlier today, we might have been getting killed by quay.io being down or intermittently down, so the image pulls were taking forever. I seem to be hitting that now at least.

**Comment by escattone** [comment]
@metadave Scratch

**Comment by metadave** [comment]
@escattone ah, good point, the quay outage was definitely messing with our testing.

**Comment by escattone** [comment]
Here's my current recommendation on the MySQL Helm chart. Since we're eventually going to use a hosted database solution (AWS RDS PostgreSQL or MySQL), there's no need to use the Helm chart for now. We can take from the current Helm chart what we need to create our own config, like this:
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ MYSQL_NAME }}
spec:
  capacity:
    storage: {{ MYSQL_STORAGE_SIZE }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ MYSQL_STORAGE_RECLAIM_POLICY }}
  awsElasticBlockStore:
    fsType: ext4
    volumeID: {{ MYSQL_STORAGE_EBS_ARN }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ MYSQL_NAME }}
  labels:
    app: {{ MYSQL_NAME }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ MYSQL_STORAGE_SIZE }}
  volumeName: {{ MYSQL_NAME }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ MYSQL_NAME }}
  labels:
    app: {{ MYSQL_NAME }}
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: {{ MYSQL_NAME }}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ MYSQL_NAME }}
  labels:
    app: {{ MYSQL_NAME }}
spec:
  template:
    metadata:
      labels:
        app: {{ MYSQL_NAME }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
              {
                  "name": "remove-lost-found",
                  "image": "busybox:1.25.0",
                  "command": ["rm", "-fr", "/var/lib/mysql/lost+found"],
                  "volumeMounts": [
                      {
                          "name": "data",
                          "mountPath": "/var/lib/mysql"
                      }
                  ],
                  "imagePullPolicy": "{{ MYSQL_IMAGE_PULL_POLICY }}"
              }
          ]'
    spec:
      containers:
      - name: {{ MYSQL_NAME }}
        image: "{{ MYSQL_IMAGE }}:{{ MYSQL_IMAGE_TAG }}"
        imagePullPolicy: {{ MYSQL_IMAGE_PULL_POLICY }}
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ MYSQL_ROOT_PASSWORD }}
        - name: MYSQL_PASSWORD
          value: {{ MYSQL_PASSWORD }}
        - name: MYSQL_USER
          value: {{ MYSQL_USER }}
        - name: MYSQL_DATABASE
          value: {{ MYSQL_DATABASE }}
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
       - name: data
         persistentVolumeClaim:
           claimName: {{ MYSQL_NAME }}
```

It's simple, we have complete control (we can avoid using storage classes for example), and eliminate the dependency on Helm.
