### ISSUE TITLE
SSL/TLS for MDN

### ISSUE THREAD

**Issue by escattone** [mozmeao/infra#414]
How are we going to handle SSL/TLS for MDN? Probably setup the AWS load balancers in the K8s cluster with certs, terminating SSL there and then everything after that is HTTP? The certs will be different for dev, stage and prod, but  can we have load balancers with different certs within the same cluster? If so, it would have to be possible to select a specific (dev) load balancer when creating the dev "web" service?

**Comment by metadave** [comment]
@escattone yes, ELB's will terminate SSL/TLS, then HTTP to K8s deployments. The LoadBalancer services simply need to use the appropriate selector for stage/prod. The only tricky part will be the dev instances, where we'll need to research using [K8s ingress](https://github.com/mozmeao/infra/issues/415).

We can request certs through the [AWS ACM](https://aws.amazon.com/certificate-manager/). I created an issue for this [here](https://github.com/mozmeao/infra/issues/416).

Instead of using our [current ELB setup](https://github.com/mozmeao/infra/tree/master/elbs), I'm thinking of using regular K8s LoadBalancers, followed by a Python/Boto script to remove the [K8s masters from the ELB instances](https://github.com/mozmeao/infra/issues/153) during service creation. We may be able to use this script with bedrock/basket/snippets/etc as well.

**Comment by metadave** [comment]
@jgmize can these certs be requested through ACM?

**Comment by metadave** [comment]
For more info on how to setup SSL for K8s load balancers:
- https://kubernetes.io/docs/concepts/services-networking/service/
    - see the section titled "SSL support on AWS"
- here's how we've used annotations in the past: https://github.com/mozmeao/infra/blob/75a8df53082bf4a491c404a817edcba6ff1db902/k8s/install/stage2_functions.sh#L258-L264
- here are the annotations in K8s Go code: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L72

**Comment by escattone** [comment]
I learned two things from talking to @metadave today:
1. AWS ELB's are created dynamically when a service type of `LoadBalancer` is specified when creating a K8s service (for some reason, I thought a pool of them had to be created manually for a K8s cluster).
2. We can specify the cert for the dynamically-created AWS ELB via an annotation on the K8s service.

Regarding the second point, see below for the actual templatized YAML that we'll use for MDN's `web` service (all of MDN's other services are of type `ClusterIP` and so are internal to the cluster).
```
kind: Service
apiVersion: v1
metadata:
  name: {{ SERVICE_NAME }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ SERVICE_CERT_ARN }}
spec:
  type: {{ SERVICE_TYPE }}
  selector:
    app: {{ SERVICE_NAME }}
  ports:
    - port: {{ SERVICE_PORT }}
      targetPort: {{ SERVICE_TARGET_PORT }}
      protocol: {{ SERVICE_PROTOCOL }}
```
We don't need to specify the first annotation, since `http` is the default value for `service.beta.kubernetes.io/aws-load-balancer-backend-protocol`, but it might be good to be explicit.
